# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BacklogCli < Formula
  desc "CLI for Backlog project management"
  homepage "https://github.com/yacchi/backlog-cli"
  version "0.18.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yacchi/backlog-cli/releases/download/v0.18.0/backlog-cli_0.18.0_darwin_amd64.tar.gz"
      sha256 "bfe9316c913388512a2d6cfc7fde982f8fab108189fe4cee612186e3e12839c2"

      define_method(:install) do
        bin.install "backlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yacchi/backlog-cli/releases/download/v0.18.0/backlog-cli_0.18.0_darwin_arm64.tar.gz"
      sha256 "5c272013e4b251b3ede91e6b53e298243b4dca6d18a01dd6402112f5b751e4fa"

      define_method(:install) do
        bin.install "backlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yacchi/backlog-cli/releases/download/v0.18.0/backlog-cli_0.18.0_linux_amd64.tar.gz"
      sha256 "2bb8c3c2caf1402f5b7d18f837b6850c3f137482a59f0344a21eb30f9b0b9022"
      define_method(:install) do
        bin.install "backlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yacchi/backlog-cli/releases/download/v0.18.0/backlog-cli_0.18.0_linux_arm64.tar.gz"
      sha256 "6da2ddf49cda5fe5c74794c09a457f954420e88fea5f83d1bcc222822e804f40"
      define_method(:install) do
        bin.install "backlog"
      end
    end
  end

  test do
    system "#{bin}/backlog", "version"
  end
end
