# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KarabinerProfileManager < Formula
  desc "Automatic Karabiner-Elements profile switcher based on connected devices"
  homepage "https://github.com/yacchi/karabiner-profile-manager"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/yacchi/karabiner-profile-manager/releases/download/v0.1.0/karabiner-profile-manager_0.1.0_darwin_amd64.tar.gz"
    sha256 "33a56348c751badc7cc2fa1b333d30cc3f3aea1452bf0561b536675b03346557"

    define_method(:install) do
      bin.install "karabiner-profile-manager"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/yacchi/karabiner-profile-manager/releases/download/v0.1.0/karabiner-profile-manager_0.1.0_darwin_arm64.tar.gz"
    sha256 "196a6bb2f52552dc17a68d3421ab526d434bef803ba41c68fefaf2605312c7e7"

    define_method(:install) do
      bin.install "karabiner-profile-manager"
    end
  end

  def caveats
    <<~EOS
      Before running `brew services start karabiner-profile-manager`, write
      a config file at:

        ${XDG_CONFIG_HOME:-$HOME/.config}/karabiner-profile-manager/config.json

      Run `karabiner-profile-manager list` to find the device IDs to put in it.
    EOS
  end

  service do
    run [opt_bin/"karabiner-profile-manager", "watch"]
    keep_alive true
    run_at_load true
    log_path var/"log/karabiner-profile-manager.log"
    error_log_path var/"log/karabiner-profile-manager.log"
  end

  test do
    system "#{bin}/karabiner-profile-manager", "version"
  end
end
