# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Statusloom < Formula
  desc "Statusline tool for Claude Code and other coding agents"
  homepage "https://github.com/yacchi/statusloom"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yacchi/statusloom/releases/download/v0.0.1/statusloom_0.0.1_darwin_amd64.tar.gz"
      sha256 "c45196bf36b8047070d6d42aeb306d2eb69508ab65d7b515e697c4fb4d2215c8"

      define_method(:install) do
        bin.install "statusloom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yacchi/statusloom/releases/download/v0.0.1/statusloom_0.0.1_darwin_arm64.tar.gz"
      sha256 "d7911c0a8b66e5d6ae9a1816507d2c4bd60f4847558d6dd6bb8d29e57947ffb8"

      define_method(:install) do
        bin.install "statusloom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yacchi/statusloom/releases/download/v0.0.1/statusloom_0.0.1_linux_amd64.tar.gz"
      sha256 "3b668ab497ceb7da21ea115c54153e552a7e2696eff32b025a6cf4d77171b0fa"
      define_method(:install) do
        bin.install "statusloom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yacchi/statusloom/releases/download/v0.0.1/statusloom_0.0.1_linux_arm64.tar.gz"
      sha256 "0ce810946ec62ccd992ffaece1c25fb4cdb83ec35447954a10a28e67753643ad"
      define_method(:install) do
        bin.install "statusloom"
      end
    end
  end

  test do
    system "#{bin}/statusloom", "version"
  end
end
