# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Statusloom < Formula
  desc "Statusline tool for Claude Code and other coding agents"
  homepage "https://github.com/yacchi/statusloom"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yacchi/statusloom/releases/download/v0.0.4/statusloom_0.0.4_darwin_amd64.tar.gz"
      sha256 "b77011541f4e7f0d2c355ff3de206cd09b6a2e5b4ef09a8697d8df91d382c273"

      define_method(:install) do
        bin.install "statusloom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yacchi/statusloom/releases/download/v0.0.4/statusloom_0.0.4_darwin_arm64.tar.gz"
      sha256 "f2bb45c963f44f9b3b26927bfdc9fae684205f7a8b532cd9d1f5d9956904d5e3"

      define_method(:install) do
        bin.install "statusloom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yacchi/statusloom/releases/download/v0.0.4/statusloom_0.0.4_linux_amd64.tar.gz"
      sha256 "0c471e1b3419d6378d4a243e014e1fba2216432e2d205db10b1058e4fd792eda"
      define_method(:install) do
        bin.install "statusloom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yacchi/statusloom/releases/download/v0.0.4/statusloom_0.0.4_linux_arm64.tar.gz"
      sha256 "b2d74258fe2109b48a5b1d0a32901848ac10cd58aa295b0b0bc9209ee4a57a05"
      define_method(:install) do
        bin.install "statusloom"
      end
    end
  end

  test do
    system "#{bin}/statusloom", "version"
  end
end
